export interface CountryDialCode {
  name: string;
  dialCode: string;
  code: string;
}

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { name: "India", dialCode: "+91", code: "IN" },
  { name: "United States", dialCode: "+1", code: "US" },
  { name: "United Kingdom", dialCode: "+44", code: "GB" },
  { name: "United Arab Emirates", dialCode: "+971", code: "AE" },
  { name: "Australia", dialCode: "+61", code: "AU" },
  { name: "Canada", dialCode: "+1", code: "CA" },
  { name: "Germany", dialCode: "+49", code: "DE" },
  { name: "France", dialCode: "+33", code: "FR" },
  { name: "Singapore", dialCode: "+65", code: "SG" },
  { name: "Switzerland", dialCode: "+41", code: "CH" },
  { name: "Netherlands", dialCode: "+31", code: "NL" },
  { name: "Spain", dialCode: "+34", code: "ES" },
  { name: "Italy", dialCode: "+39", code: "IT" },
  { name: "Sweden", dialCode: "+46", code: "SE" },
  { name: "Norway", dialCode: "+47", code: "NO" },
  { name: "Denmark", dialCode: "+45", code: "DK" },
  { name: "New Zealand", dialCode: "+64", code: "NZ" },
  { name: "Japan", dialCode: "+81", code: "JP" },
  { name: "South Africa", dialCode: "+27", code: "ZA" },
  { name: "Saudi Arabia", dialCode: "+966", code: "SA" },
  { name: "Qatar", dialCode: "+974", code: "QA" },
  { name: "Kuwait", dialCode: "+965", code: "KW" },
  { name: "Oman", dialCode: "+968", code: "OM" },
  { name: "Bahrain", dialCode: "+973", code: "BH" },
  { name: "Austria", dialCode: "+43", code: "AT" },
  { name: "Belgium", dialCode: "+32", code: "BE" },
  { name: "Brazil", dialCode: "+55", code: "BR" },
  { name: "China", dialCode: "+86", code: "CN" },
  { name: "Czech Republic", dialCode: "+420", code: "CZ" },
  { name: "Egypt", dialCode: "+20", code: "EG" },
  { name: "Finland", dialCode: "+358", code: "FI" },
  { name: "Greece", dialCode: "+30", code: "GR" },
  { name: "Hong Kong", dialCode: "+852", code: "HK" },
  { name: "Hungary", dialCode: "+36", code: "HU" },
  { name: "Indonesia", dialCode: "+62", code: "ID" },
  { name: "Ireland", dialCode: "+353", code: "IE" },
  { name: "Israel", dialCode: "+972", code: "IL" },
  { name: "Malaysia", dialCode: "+60", code: "MY" },
  { name: "Mexico", dialCode: "+52", code: "MX" },
  { name: "Nepal", dialCode: "+977", code: "NP" },
  { name: "Philippines", dialCode: "+63", code: "PH" },
  { name: "Poland", dialCode: "+48", code: "PL" },
  { name: "Portugal", dialCode: "+351", code: "PT" },
  { name: "Romania", dialCode: "+40", code: "RO" },
  { name: "Russia", dialCode: "+7", code: "RU" },
  { name: "South Korea", dialCode: "+82", code: "KR" },
  { name: "Sri Lanka", dialCode: "+94", code: "LK" },
  { name: "Thailand", dialCode: "+66", code: "TH" },
  { name: "Turkey", dialCode: "+90", code: "TR" },
  { name: "Vietnam", dialCode: "+84", code: "VN" },
];

export const WORLD_COUNTRIES: string[] = [
  "India",
  "United States",
  "United Kingdom",
  "United Arab Emirates",
  "Australia",
  "Canada",
  "Germany",
  "France",
  "Singapore",
  "Switzerland",
  "Netherlands",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "New Zealand",
  "Japan",
  "South Africa",
  "Saudi Arabia",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "Georgia",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Maldives",
  "Malta",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Nepal",
  "Nigeria",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "South Korea",
  "Sri Lanka",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Zimbabwe",
  "Other",
];
